version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: uk.gov.hmcts.reform:ecm-common
    versions:
    - 0.1.15
    - 0.1.16
    - 0.1.17
    - 0.1.18
    - 0.1.19
    - 0.1.20
    - 0.1.21
    - 0.1.22
    - 0.1.24
    - 0.1.26
    - 0.1.27
    - 0.1.28
    - 0.1.29
    - 0.1.32
    - 0.1.55
    - 0.1.57
    - 0.1.58
    - 0.1.59
    - 0.1.60
    - 0.1.61
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: com.nimbusds:nimbus-jose-jwt
    versions:
    - 9.4.1
    - 9.4.2
    - "9.5"
    - "9.6"
    - "9.7"
    - "9.8"
    - 9.8.1
  - dependency-name: org.owasp.dependencycheck
    versions:
    - 6.1.3
    - 6.1.4
  - dependency-name: org.postgresql:postgresql
    versions:
    - 42.2.19
  - dependency-name: net.javacrumbs.shedlock:shedlock-spring
    versions:
    - 4.20.0
    - 4.20.1
    - 4.21.0
    - 4.22.0
    - 4.22.1
  - dependency-name: org.springframework.boot:spring-boot-starter-test
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.bouncycastle:bcpkix-jdk15on
    versions:
    - "1.68"
  - dependency-name: org.springframework.cloud:spring-cloud-starter-openfeign
    versions:
    - 3.0.1
    - 3.0.2
  - dependency-name: org.sonarqube
    versions:
    - 3.1.1
  - dependency-name: net.serenity-bdd:serenity-core
    versions:
    - 2.3.12
    - 2.3.13
    - 2.3.30
    - 2.3.31
  - dependency-name: net.serenity-bdd:serenity-rest-assured
    versions:
    - 2.3.12
    - 2.3.13
    - 2.3.30
    - 2.3.31
  - dependency-name: net.serenity-bdd:serenity-spring
    versions:
    - 2.3.12
    - 2.3.13
    - 2.3.30
    - 2.3.31
  - dependency-name: net.serenity-bdd:serenity-junit
    versions:
    - 2.3.12
    - 2.3.13
    - 2.3.30
    - 2.3.31
