java:
  environment:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    ethos-shared:
      resourceGroup: ethos
      secrets:
        - ecm-consumer-s2s-key
        - caseworker-user-name
        - caseworker-password
