java:
  environment:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    ethos-shared:
      resourceGroup: ethos
      secrets:
        - ecmConsumerS2sKey
        - caseworkerUsername
        - caseworkerPassword
