java:
  environment:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    ethos:
      resourceGroup: ecm-consumer
      secrets:
        - ecm-consumer-s2s-secret
